services:
    - mysql

language: perl6

perl6:
  - latest

env:
  - ALL_TESTING=1

before_install:
  - mysql -e "create database perltest" -uroot
  - mysql -e "create user 'perltest'@'localhost' identified by 'testpass'" -uroot
  - mysql -e "grant all privileges on perltest.* to 'perltest'@'localhost'" -uroot
  - cp t/.my.cnf ~

after_install:
  - rm ~/.my.cnf

install:
  - rakudobrew build-zef
  - zef -v install --deps-only .
